### ISSUE TITLE
This SDK violates intellectual property rights!

### ISSUE THREAD

**Issue by KirillKuzyk** [Phantomxm2021/ARMOD-Framework#1]
Hy guys,

This is Kirill, creator of the AR Foundation Editor Remote plugin:
https://assetstore.unity.com/packages/tools/utilities/ar-foundation-editor-remote-168773

I would love to congratulate you on the ARMOD launch, but it turned out that you've included my plugin inside your SDK.
The AR Foundation Editor Remote is a paid tool and you can't just include it inside in your SDK even if you've purchased a license.

Please remove the ARMOD Debuger from your SDK because it violates my intellectual property rights. I hope for your understanding.

**Comment by Phantomxm2021** [comment]
> Hy guys,
> 
> This is Kirill, creator of the AR Foundation Editor Remote plugin:
> https://assetstore.unity.com/packages/tools/utilities/ar-foundation-editor-remote-168773
> 
> I would love to congratulate you on the ARMOD launch, but it turned out that you've included my plugin inside your SDK.
> The AR Foundation Editor Remote is a paid tool and you can't just include it inside in your SDK even if you've purchased a license.
> 
> Please remove the ARMOD Debuger from your SDK because it violates my intellectual property rights. I hope for your understanding.

I sincerely say sorry to you. I will remove all plug-in information about you immediately.
If there are users who need to use Remote, I will recommend users to use your plug-in.

**Comment by KirillKuzyk** [comment]
Thank you!
