### ISSUE TITLE
[BUG]官网无法使用

### ISSUE THREAD

**Issue by AmosHuKe** [Phantomxm2021/ARMOD-Framework#12]
网址：https://phantomsxr.com/signup/ 、 https://phantomsxr.com/
问题：
![image](https://user-images.githubusercontent.com/32262985/197925481-20ac91e0-e86a-4475-8dab-b5fb3e35cc2e.png)

**Comment by Phantomxm2021** [comment]
Hi AmosHuke, 
Our website has been migrated to `phantomsxr.cn`.  But note that `phantomsxr.com` and `phantomsxr.cn` data are out of sync, it is a brand new dashboard.

Best,
Phantom

**Comment by AmosHuKe** [comment]
thanks~
